# Generated by Django 3.1.2 on 2020-10-09 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscaprest', '0003_auto_20201008_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestador',
            old_name='Endereco',
            new_name='endereco',
        ),
    ]
