# Generated by Django 3.1.2 on 2020-10-21 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=30, null=True)),
                ('endereco', models.CharField(blank=True, max_length=30, null=True)),
                ('cpf', models.CharField(blank=True, max_length=30, null=True)),
                ('telefone01', models.CharField(blank=True, max_length=30, null=True)),
                ('telefone02', models.CharField(blank=True, max_length=30, null=True)),
                ('veiculo', models.CharField(blank=True, max_length=30, null=True)),
                ('rastreador', models.CharField(blank=True, max_length=30, null=True)),
                ('instalado', models.BooleanField(default=False)),
                ('data_instalcao', models.CharField(blank=True, max_length=30, null=True)),
                ('retirado', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
