# Generated by Django 3.1.2 on 2020-10-22 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20201021_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_instalcao',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='instalado',
            field=models.CharField(choices=[('SIM', 'sim'), ('NAO', 'nao')], max_length=3),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='retirado',
            field=models.CharField(choices=[('SIM', 'sim'), ('NAO', 'nao')], max_length=3),
        ),
    ]
